# Generated by Django 5.0.4 on 2026-07-25 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('top_path', models.CharField(blank=True, max_length=300)),
                ('top_referrer', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('building', 'Building'), ('learning', 'Learning'), ('reading', 'Reading'), ('focused', 'Focused on')], default='building', max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Now entries',
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('live', 'Live'), ('paused', 'Paused'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('problem', models.TextField(blank=True, help_text='Markdown. What problem is this solving?')),
                ('approach', models.TextField(blank=True, help_text='Markdown. How are you approaching it?')),
                ('progress', models.TextField(blank=True, help_text='Markdown. Where things stand.')),
                ('lessons', models.TextField(blank=True, help_text='Markdown. What you have learned.')),
                ('cover', models.ImageField(blank=True, upload_to='projects/')),
                ('url', models.URLField(blank=True, help_text='Live site, if there is one.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(default='Siphira John', max_length=120)),
                ('hero_tagline', models.CharField(default='Merchandiser, brand ambassador, and founder — building at the intersection of beauty, healthcare, and technology.', max_length=300)),
                ('hero_intro', models.TextField(default="I'm Siphira — a Nairobi-based merchandiser and field sales professional with a background in beauty, skincare, and haircare brand representation, and a certificate in orthopaedic and trauma medicine. I’m currently building something new. This site is where I document that journey.")),
                ('about_body', models.TextField(blank=True, help_text='Markdown. The full About page narrative.')),
                ('now_intro', models.CharField(default="What I'm currently building, learning, reading, and focused on.", max_length=300)),
                ('blog_intro', models.CharField(default='I write about entrepreneurship, technology, healthcare, AI, and design — reflections, tutorials, and lessons learned along the way.', max_length=300)),
                ('email', models.EmailField(default='siphirawanjiku0@gmail.com', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/siphira-john-b3b1a3314')),
                ('twitter_url', models.URLField(blank=True, help_text='Full URL to the X/Twitter profile. Leave blank to hide.')),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=100)),
                ('portrait', models.ImageField(blank=True, help_text='Overrides the bundled headshot if set.', upload_to='portraits/')),
                ('cv', models.FileField(blank=True, help_text='Overrides the bundled CV PDF if set.', upload_to='cv/')),
                ('comments_enabled', models.BooleanField(default=True, help_text='Global switch for blog comments.')),
                ('feedback_enabled', models.BooleanField(default=True, help_text='Show the "was this useful?" widget on posts.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Shown on the blog index and in link previews.', max_length=400)),
                ('body', models.TextField(help_text='Markdown supported.')),
                ('cover', models.ImageField(blank=True, upload_to='posts/')),
                ('cover_alt', models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated.', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time', models.PositiveIntegerField(default=1, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='site.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('referrer_host', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('visitor', models.CharField(db_index=True, max_length=32)),
                ('is_new_visitor', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='site.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('sentiment', models.CharField(choices=[('up', 'Helpful'), ('down', 'Not helpful')], max_length=10)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='site.post')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Never shown publicly.', max_length=254)),
                ('body', models.TextField(max_length=3000)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='site.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/shots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='site.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Markdown.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='site.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='site.skillgroup')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at', 'is_published'], name='site_post_publish_159f75_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['-created_at', 'path'], name='site_pagevi_created_26f687_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved', '-created_at'], name='site_commen_is_appr_e7fded_idx'),
        ),
    ]
